

GET http://localhost:8080/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYm9uZ3kiLCJpYXQiOjE2MTY1NjY0MTEsImV4cCI6MTYxNjU2NjQ1MX0.x9C-c6KVYwK9CnUSpD4wv5njE2HqhOl4YlcZiLt73DA

###

DELETE  http://localhost:4000/logout
Content-Type : application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYm9uZ3kiLCJpYXQiOjE2MTY1NjYzNjd9.gXZ41izNZ6n8e1s2AKLeFDUJNyvuRex-aB6zAKvysYk"
}

###
POST http://localhost:4000/token
Content-Type : application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYm9uZ3kiLCJpYXQiOjE2MTY1NjYzNjd9.gXZ41izNZ6n8e1s2AKLeFDUJNyvuRex-aB6zAKvysYk"
}

###

POST http://localhost:4000/login
Content-Type : application/json

{
    "username" : "bongy"
}